[workspace]
members = [
    "crates/opendefocus",
    "crates/opendefocus-shared",
    "crates/opendefocus-kernel",
    "crates/opendefocus-datastructure",
    "crates/opendefocus-nuke",
    "xtask",
    "examples/simple",
]
exclude = ["crates/spirv-cli-build"]
resolver = "2"


[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
    'cfg(target_arch, values("spirv"))',
] }


[workspace.package]
version = "0.1.4"
authors = ["olivebowl <olivebowl@noreply.codeberg.org>"]
edition = "2024"
license = "EUPL-1.2"
repository = "https://codeberg.org/opendefocus/opendefocus"
homepage = "https://opendefocus.codeberg.page"
documentation = "https://docs.rs/opendefocus/"
keywords = ["defocus", "convolution", "image-processing"]
categories = ["multimedia", "graphics"]
readme = "README.md"

[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3
