use anyhow::{Error, Result};
use duct::cmd;
use naga::{back::wgsl::WriterFlags, front::spv::Options};

use crate::util::crate_root;

pub async fn compile_spirv() -> Result<()> {
    log::info!("Starting spirv build");
    let spirv_path = cmd!(
        "cargo",
        "+nightly-2025-06-30",
        "run",
        "--manifest-path",
        crate_root()
            .join("crates")
            .join("spirv-cli-build")
            .join("Cargo.toml"),
        "--release",
        "--",
        "-c",
        crate_root().join("crates").join("opendefocus-kernel"),
        "-o",
        "./",
        "--print-output",
    )
    .read()?
    .lines()
    .last()
    .ok_or(Error::msg("Command did not have a last line."))?
    .to_string();

    log::info!("Spirv shader compiled to {spirv_path}");

    let module =
        naga::front::spv::parse_u8_slice(&tokio::fs::read(spirv_path).await?, &Options::default())?;
    let module_info: naga::valid::ModuleInfo = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    )
    .subgroup_stages(naga::valid::ShaderStages::all())
    .subgroup_operations(naga::valid::SubgroupOperationSet::all())
    .validate(&module)?;
    let wgsl = naga::back::wgsl::write_string(&module, &module_info, WriterFlags::empty())?;
    let wgsl = format!(
        "// This file is automatically generated by xtask. Do not modify manually.\n// License: https://opendefocus.codeberg.page/license.html\n// Automatic spirv generation by Rust-GPU https://github.com/rust-gpu/rust-gpu\n\n{wgsl}"
    );
    tokio::fs::write(
        crate_root().join("shaders").join("opendefocus-kernel.wgsl"),
        wgsl,
    )
    .await?;
    Ok(())
}
