name: "Nuke build"

on:
  push:
    # tags:
    #   - 'v*'
    # branches:
    #   - 'main'
env:
  NUKE_VERSIONS: "13.0,13.1,13.2,14.0,14.1,15.0,15.1,15.2,16.0"
  RUST_BACKTRACE: "1"

permissions:
  contents: read

jobs:

  linux:
    runs-on: ubuntu-latest
    name: linux
    steps:
      - &ci-pending-status
        name: Set CI status
        shell: bash
        run: |
          curl -X POST "https://codeberg.org/api/v1/repos/olivebowl/opendefocus/statuses/${{ github.sha }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.CODEBERG_RELEASE_TOKEN }}" \
            -d '{
                  "context": "ci/github/${{ github.event_name}}/${{ github.workflow }}/${{ github.job }}",
                  "state": "pending",
                  "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }'

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-codeql: "true"
          remove-haskell: "true"

      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - name: Build
        run: |
          docker run --rm -v $(pwd):/opendefocus quay.io/pypa/manylinux2014_x86_64:latest /bin/bash -c "
              yum -y update && \
              yum install -y openssl-devel && \
              curl https://sh.rustup.rs -sSf | sh -s -- -y && \
              source ~/.bashrc && \
              cd /opendefocus && \
              cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} \
              --limit-threads --target-platform linux --build-protoc --output-to-package
          "

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-linux
          path: package

      - &ci-finished
        name: Set CI status
        shell: bash
        if: always()
        run: |
          curl -X POST "https://codeberg.org/api/v1/repos/olivebowl/opendefocus/statuses/${{ github.sha }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.CODEBERG_RELEASE_TOKEN }}" \
            -d '{
                  "context": "ci/github/${{ github.event_name}}/${{ github.workflow }}/${{ github.job }}",
                  "state": "${{ job.status }}",
                  "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }'


  windows:
    runs-on: windows-2022
    name: windows
    steps:
      - *ci-pending-status
      - uses: actions/checkout@v6

      - name: Setup instance
        run: choco install lessmsi protoc -y

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - name: Build
        run: cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} --limit-threads --target-platform windows --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-windows
          path: package

      - *ci-finished

  macos:
    strategy:
      matrix:
        platform:
          - runner: macos-15-intel
            target: macos-x86-64
          - runner: macos-latest
            target: macos-aarch64
    name: ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - *ci-pending-status
      - uses: actions/checkout@v6
      - name: Setup required tools
        run: brew install protobuf

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "CARGO CC CFLAGS CXX CMAKE RUST NUKE_VERSIONS"

      - uses: nick-fields/retry@v2
        name: Build
        with:
          timeout_minutes: 100
          max_attempts: 3
          command: cargo xtask --compile --nuke-versions ${{ env.NUKE_VERSIONS }} --limit-threads --target-platform ${{ matrix.platform.target }} --output-to-package

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: nuke-${{ matrix.platform.target }}
          path: package

      - *ci-finished

  release:
    runs-on: ubuntu-latest
    name: release
    needs: [linux, windows, macos]
    steps:
      - *ci-pending-status

      - uses: actions/checkout@v6

      - name: Setup instance
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cargo-about

      - uses: actions/download-artifact@v5
        with:
          path: package
          merge-multiple: true

      - name: Release
        run: cargo xtask --release-package
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CODEBERG_RELEASE_TOKEN: ${{ secrets.CODEBERG_RELEASE_TOKEN }}
          WOODPECKER_ACCESS_TOKEN: ${{ secrets.WOODPECKER_ACCESS_TOKEN }}

      - name: Release
        run: cargo xtask --release-package --target-package-path ./release-candidate.zip
        if: startsWith(github.ref, 'refs/tags/v') != true
        env:
          CODEBERG_RELEASE_TOKEN: ${{ secrets.CODEBERG_RELEASE_TOKEN }}
          WOODPECKER_ACCESS_TOKEN: ${{ secrets.WOODPECKER_ACCESS_TOKEN }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v') != true
        with:
          name: release-candidate
          path: release-candidate.zip

      - *ci-finished
